//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gr681shiacurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class customs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customs()
        {
            this.OrderTIcket = new HashSet<OrderTIcket>();
        }
    
        public int idcustoms { get; set; }
        public string Baggage { get; set; }
        public int Weight { get; set; }
        public string Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTIcket> OrderTIcket { get; set; }
    }
}
