//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gr681shiacurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightTicket()
        {
            this.OrderTIcket = new HashSet<OrderTIcket>();
        }
    
        public int idFlightTicket { get; set; }
        public int idFlight { get; set; }
        public int ifTicket { get; set; }
        public int Allseats { get; set; }
        public int ordered { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Ticket Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTIcket> OrderTIcket { get; set; }
    }
}
