//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gr681shiacurs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirportSHIAEntities : DbContext
    {
        public AirportSHIAEntities()
            : base("name=AirportSHIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<customs> customs { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<FlightTicket> FlightTicket { get; set; }
        public virtual DbSet<OrderTIcket> OrderTIcket { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Usersystem> Usersystem { get; set; }
    }
}
