//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gr681shiacurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTIcket
    {
        public int idOrderTicket { get; set; }
        public int idFlightTicket { get; set; }
        public int idUserSystem { get; set; }
        public int idClient { get; set; }
        public string Dateorder { get; set; }
        public string NumberOrder { get; set; }
        public string StatusOrder { get; set; }
        public int idcustomers { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual customs customs { get; set; }
        public virtual FlightTicket FlightTicket { get; set; }
        public virtual Usersystem Usersystem { get; set; }
    }
}
