//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gr681shiacurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usersystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usersystem()
        {
            this.OrderTIcket = new HashSet<OrderTIcket>();
        }
    
        public int idUser { get; set; }
        public string LastName { get; set; }
        public string Firstname { get; set; }
        public string MiddleName { get; set; }
        public string PhoneNumber { get; set; }
        public string Adress { get; set; }
        public string Role { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTIcket> OrderTIcket { get; set; }
    }
}
